name: 'cdgc_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets: [ 'target','dbt_packages' ]

models:
  cdgc_demo:
    staging:
      database: DEV_STAGING_DB
      schema: STAGING
      +materialized: view
      +schema: staging
      tags:
        [staging]
    intermediate:
      database: DEV_PRESENTATION_DB
      schema: INTERMEDIATE
      +materialized: table
      +schema: intermediate
    marts:
      database: DEV_MARTS_DB
      schema: MARTS
      +materialized: table
      +schema: marts